#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

# I don't remember why
# I had this shebang
# so let's have it just in case
# until next test
#!/data/data/com.termux/files/usr/bin/env bash

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
source \
  "${_crash_bash}"

_root_requirements() {
  _check_cmd \
    "su"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  get_mode=""
  color=""
  quiet=""
}

_sdk_version() {
  local \
    _mode="${1}" \
    _cmd=() \
    _sdk_version_keyvalue \
    _version
  _cmd=(
    grep
      ro.build.version.sdk=
      '/system/build.prop'
  )
  _sdk_version_keyvalue="$( \
    su \
      -c \
      "${_cmd[*]}")"
  _version="$( \
    echo \
      "${_sdk_version_keyvalue}" | \
      awk \
        -F \
          '=' \
        '{print $2}')"
  echo \
    "${_version}"
}

_auto_detect_mode() {
  local \
    _msg=()
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Tell me when somebody will"
      "have merged GNU with Andro-"
      "wait a sec"
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Got activity at date:   ${get_date}"
  _msg_info "                 Get mode:   ${get_mode}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Get currently focused Android activity

Usage:
  $(_get "app" "name")
    [options]
  options:
     -m <method>          Method to obtain activity name.
                          Default: ${get_mode}
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    m) override_get_mode="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg_error \
        "Invalid argument '${arg}'" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
)
_show_config
_sdk_version \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
